// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwov0Y5Fmh_zbSxi8SIiuXud1Mxlumh6w',
    appId: '1:224015384929:web:7d93a358e990b6a08c4520',
    messagingSenderId: '224015384929',
    projectId: 'projeto-iris-puc',
    authDomain: 'projeto-iris-puc.firebaseapp.com',
    storageBucket: 'projeto-iris-puc.appspot.com',
    measurementId: 'G-JNJWX1CTPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnI2QPa6FOOHbWitvGDrXwgZMklTPJYhc',
    appId: '1:224015384929:android:05df23c0399a7c188c4520',
    messagingSenderId: '224015384929',
    projectId: 'projeto-iris-puc',
    storageBucket: 'projeto-iris-puc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuO3M40IX0HOHFmGRkW_vYCpoOuskZy00',
    appId: '1:224015384929:ios:42536d4fc4717ee68c4520',
    messagingSenderId: '224015384929',
    projectId: 'projeto-iris-puc',
    storageBucket: 'projeto-iris-puc.appspot.com',
    iosBundleId: 'com.example.irisApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuO3M40IX0HOHFmGRkW_vYCpoOuskZy00',
    appId: '1:224015384929:ios:b26ac81b70bc80158c4520',
    messagingSenderId: '224015384929',
    projectId: 'projeto-iris-puc',
    storageBucket: 'projeto-iris-puc.appspot.com',
    iosBundleId: 'com.example.irisApp.RunnerTests',
  );
}
